{
 "title": "HDS: Historical HSD Details",
 "description": "Host Storage Domain Details - Historical data based on Export Tool dump",
 "tags": [
  "HDS",
  "Historical"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.perf.physical.*" },
   { "name": "System", "query": "hds.perf.physical.$Type.*" },
   {
    "name": "HSD",
    "query": "hds.perf.physical.$Type.$System.LU.*.*"
   }
  ]
 },
 "panels": [
  { "title": "HSD Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HSD IOPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(consolidateBy(sumSeriesWithWildcards(hds.perf.physical.$Type.$System.LU.CL[1357]*.$HSD.*.IOPS, 8), 'max')), 7)"
    }
   ]
  },
  {
   "title": "HSD Throughput",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(consolidateBy(sumSeriesWithWildcards(hds.perf.physical.$Type.$System.LU.CL[1357]*.$HSD.*.TRANSFER, 8), 'max')), 7)"
    }
   ]
  },
  {
   "title": "HSD Average Latency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(consolidateBy(averageSeriesWithWildcards(hds.perf.physical.$Type.$System.LU.CL[1357]*.$HSD.*.LATENCY, 8), 'max')), 7)"
    }
   ]
  },
  { "title": "HSD Performance Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "HSD Read / Write Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.physical.$Type.$System.LU.CL[1357]*.$HSD.*.READ_TRANSFER, 8), 7, 8)"
    },
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.physical.$Type.$System.LU.CL[1357]*.$HSD.*.WRITE_TRANFER, 8), 7, 8)"
    }
   ]
  },
  {
   "title": "HSD Read / Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeriesWithWildcards(hds.perf.physical.$Type.$System.LU.CL[1357]*.$HSD.*.READ_LATENCY, 8), 7, 8)"
    },
    {
     "target": "aliasByNode(averageSeriesWithWildcards(hds.perf.physical.$Type.$System.LU.CL[1357]*.$HSD.*.WRITE_LATENCY, 8), 7, 8)"
    }
   ]
  },
  {
   "title": "HSD Read / Write Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent(sumSeries(hds.perf.physical.$Type.$System.LU.*.$HSD.*.READ_TRANSFER), #C), 'READ')",
     "targetFull": "alias(asPercent(sumSeries(hds.perf.physical.$Type.$System.LU.*.$HSD.*.READ_TRANSFER), sumSeries(hds.perf.$Type.$System.LU.*.$HSD.*.TRANSFER)), 'READ')"
    },
    {
     "target": "alias(asPercent(sumSeries(hds.perf.physical.$Type.$System.LU.*.$HSD.*.WRITE_TRANFER), #C), 'WRITE')",
     "targetFull": "alias(asPercent(sumSeries(hds.perf.physical.$Type.$System.LU.*.$HSD.*.WRITE_TRANFER), sumSeries(hds.perf.$Type.$System.LU.*.$HSD.*.TRANSFER)), 'WRITE')"
    }
   ]
  },
  {
   "title": "HSD Average IO Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(sumSeries(hds.perf.physical.$Type.$System.LU.*.$HSD.*.TRANSFER), #A), 'Average IO Size')",
     "targetFull": "alias(divideSeries(sumSeries(hds.perf.physical.$Type.$System.LU.*.$HSD.*.TRANSFER), alias(sumSeries(hds.perf.$Type.$System.LU.*.$HSD.*.IOPS), 'READ')), 'Average IO Size')"
    }
   ]
  },
  {
   "title": "Average HSD IO Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "divideSeries(averageSeries(hds.perf.physical.$Type.$System.LU.*.$HSD.*.TRANSFER), #A)",
     "targetFull": "divideSeries(averageSeries(hds.perf.physical.$Type.$System.LU.*.$HSD.*.TRANSFER), averageSeries(hds.perf.$Type.$System.LU.*.$HSD.*.IOPS))"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "HSD Capacity for $HSD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.lu.$HSD.*.capacity), 'Capacity')"
    },
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.lu.$HSD.*.used), 'Used')"
    }
   ]
  },
  {
   "title": "Tier usage for $HSD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.lu.$HSD.*.tier3), 'Tier 3')"
    },
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.lu.$HSD.*.tier2), 'Tier 2')"
    },
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.lu.$HSD.*.tier1), 'Tier 1')"
    }
   ]
  },
  { "title": "LUN Performace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "LU IOPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.LU.CL[1357]*.$HSD.*.IOPS, 7, 8)"
    }
   ]
  },
  {
   "title": "LU Throughput",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(hds.perf.physical.$Type.$System.LU.CL[1357]*.$HSD.*.TRANSFER), 7, 8)"
    }
   ]
  },
  {
   "title": "LU Latency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.LU.CL[1357]*.$HSD.*.LATENCY, 7, 8)"
    }
   ]
  }
 ]
}