{
 "title": "HDS: Historical Port Details",
 "description": "FrontEnd Port Details - Historical data based on Export Tool dump",
 "tags": [
  "HDS",
  "Historical"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.perf.physical.*" },
   { "name": "System", "query": "hds.perf.physical.$Type.*" },
   {
    "name": "Port",
    "query": "hds.perf.physical.$Type.$System.PORT.*"
   }
  ]
 },
 "panels": [
  { "title": "Port Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Port: Port IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.PORT.$Port.IOPS, 4, 6)"
    }
   ]
  },
  {
   "title": "$Port: Port Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.PORT.$Port.TRANSFER, 4, 6)"
    }
   ]
  },
  {
   "title": "$Port: Port Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.PORT.$Port.LATENCY, 4, 6)"
    }
   ]
  },
  {
   "title": "Port Performance (stacked)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Port: Port IOPS (stacked)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.$Type.$System.PORT.$Port.IOPS, 4,6)"
      }
     ]
    },
    {
     "title": "$Port: Port Durchsatz (stacked)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.$Type.$System.PORT.$Port.TRANSFER, 4, 6)"
      }
     ]
    },
    {
     "title": "$Port: Port Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.$Type.$System.PORT.$Port.LATENCY, 4, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "HSD Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Port: IOPS nach Host Storage Domains",
     "type": "graph",
     "description": "Entspricht der Gesamtanzahl an IOPS aller LDEVs in der HSD.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(removeEmptySeries(sumSeriesWithWildcards(hds.perf.physical.$Type.$System.LU.$Port.*.*.IOPS, 8)), 7)"
      }
     ]
    },
    {
     "title": "$Port: Durchsatz nach Host Storage Domains",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(removeEmptySeries(sumSeriesWithWildcards(hds.perf.physical.$Type.$System.LU.$Port.*.*.TRANSFER, 8)), 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Top LUs on Port",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top LUs on Port $Port by IOPS",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.$Type.$System.LU.$Port.*.*.IOPS, 5), 4, 6, 7, 8)"
      }
     ]
    },
    {
     "title": "Top LUs on Port $Port by Throughput",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.$Type.$System.LU.$Port.*.*.TRANSFER, 5), 4, 6, 7, 8)"
      }
     ]
    },
    {
     "title": "Top LUs on Port $Port by Latency",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.$Type.$System.LU.$Port.*.*.LATENCY, 5), 4, 6, 7, 8)"
      }
     ]
    }
   ]
  }
 ]
}