{
 "title": "HDS: Historical Pool Statistics",
 "description": "Historical data based on Export Tool dump",
 "tags": [
  "HDS",
  "Historical"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.perf.physical.*" },
   { "name": "System", "query": "hds.perf.physical.$Type.*" },
   {
    "name": "Pool",
    "query": "hds.perf.physical.$Type.$System.LDEV.DP.*"
   }
  ]
 },
 "panels": [
  { "title": "Volume Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volumecount for $System and Pools: $Pool",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "sumSeries(hds.capacity.$Type.$System.pool.$Pool.volumecount)"
    }
   ]
  },
  {
   "title": "Volume Count over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.pool.$Pool.volumecount), 'Volumecount for $System and Pools: $Pool')"
    }
   ]
  },
  {
   "title": "Volume Count over Time per Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.capacity.$Type.$System.pool.$Pool.volumecount, 3, 5)"
    }
   ]
  },
  { "title": "Pool Capacities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pool Capacity for $System Pool: $Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.capacity.$Type.$System.pool.$Pool.capacity, 5, 6)"
    }
   ]
  },
  {
   "title": "Pool Used Capacity for $System Pool: $Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.capacity.$Type.$System.pool.$Pool.used, 5, 6)"
    }
   ]
  },
  { "title": "Tier Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Tier Usage for $System Pool: $Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.ldev.DP.$Pool.*.tier3), 'Tier 3')"
    },
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.ldev.DP.$Pool.*.tier2), 'Tier 2')"
    },
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.ldev.DP.$Pool.*.tier1), 'Tier 1')"
    }
   ]
  },
  {
   "title": "Tier Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.ldev.DP.$Pool.*.tier1), 'TIER1')"
    },
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.ldev.DP.$Pool.*.tier2), 'TIER2')"
    },
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.ldev.DP.$Pool.*.tier3), 'TIER3')"
    }
   ]
  }
 ]
}