{
 "title": "HDS: Historical Multiprocessor Details",
 "description": "Historical data based on Export Tool dump",
 "tags": [
  "HDS",
  "Historical"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.perf.physical.*" },
   { "name": "System", "query": "hds.perf.physical.$Type.*" }
  ]
 },
 "panels": [
  { "title": "MP Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avergage Multiprocessor Utilization for $System",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeriesWithWildcards(hds.perf.physical.$Type.$System.MP.*.UTIL, 5), 4, 5)"
    }
   ]
  },
  {
   "title": "Top 10 MPs with highest Utilization from $System",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(highestMax(hds.perf.physical.$Type.$System.MP.*.UTIL, 10)), 4, 6)"
    }
   ]
  },
  {
   "title": "MP Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "$System: MP Utilization",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(hds.perf.physical.$Type.$System.MP.*.UTIL), 4, 6)"
      }
     ]
    }
   ]
  }
 ]
}