{
 "title": "HDS: hds2graphite Statistics",
 "description": "Runtime statistics for the hds2graphite tool",
 "tags": [
  "HDS",
  "HDS2GRAPHITE"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.hds2graphite.stats.*" },
   { "name": "System", "query": "hds.hds2graphite.stats.$Type.*" }
  ]
 },
 "panels": [
  { "title": "Statistic Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.hds2graphite.stats.$Type.$System.runtime.total, 4)"
    }
   ]
  },
  {
   "title": "Total Metrics collected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.hds2graphite.stats.$Type.$System.metric.count.*.*, 7, 8, 9), 4)"
    }
   ]
  },
  { "title": "RAIDCOM Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Query for DP Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.hds2graphite.stats.$Type.$System.runtime.getdppools, 4)"
    }
   ]
  },
  {
   "title": "Query for Parity Groups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.hds2graphite.stats.$Type.$System.runtime.getpgs, 4)"
    }
   ]
  },
  {
   "title": "Query for DP-VOLs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.hds2graphite.stats.$Type.$System.runtime.getdpldev, 4)"
    }
   ]
  },
  {
   "title": "Query for PG-VOLs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.hds2graphite.stats.$Type.$System.runtime.getpgldev, 4)"
    }
   ]
  },
  { "title": "Export Tool Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Export Tool Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.hds2graphite.stats.$Type.$System.runtime.exporttool, 4)"
    }
   ]
  },
  { "title": "Send to Graphite", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Import Performance Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.hds2graphite.stats.$Type.$System.runtime.importmetric, 4)"
    }
   ]
  },
  {
   "title": "Import Pool Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.hds2graphite.stats.$Type.$System.runtime.logpoolstats, 4)"
    }
   ]
  },
  {
   "title": "Import LDEV Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.hds2graphite.stats.$Type.$System.runtime.logldevstats, 4)"
    }
   ]
  },
  {
   "title": "Import Logical Unit Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.hds2graphite.stats.$Type.$System.runtime.loglustats, 4)"
    }
   ]
  }
 ]
}