{
 "title": "HDS: Historical System Performance",
 "description": "Historical data based on Export Tool dump",
 "tags": [
  "HDS",
  "Historical"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "System", "query": "hds.perf.physical.*.*" }
  ]
 },
 "panels": [
  { "title": "System IOPS and Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total System IOPS for $System",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.*.$System.PORT.*.IOPS), '$System')"
    }
   ]
  },
  {
   "title": "Total System Throughput for $System",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.*.$System.PORT.*.TRANSFER), '$System')"
    }
   ]
  },
  { "title": "Multiprocessor Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Average Multiprocessor Utilization: $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.MP.*.UTIL), 6)"
    }
   ]
  },
  {
   "title": "Global Mutliprocessor Utilization $System",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "averageSeries(hds.perf.physical.*.$System.MP.*.UTIL)"
    }
   ]
  },
  { "title": "Cache Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "System Cache Write Pending: $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.CACHE.[0123456789]*.*.MP[BU]_WRITE_PENDING), 6, 7)"
    }
   ]
  },
  {
   "title": "Global Cache Write Pending $System",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "hds.perf.physical.*.$System.CACHE.ALL.WRITE_PENDING"
    }
   ]
  },
  {
   "title": "Global Cache Utiliation $System",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "hds.perf.physical.*.$System.CACHE.ALL.UTILIZATION"
    }
   ]
  },
  {
   "title": "System Cache Usage: $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMinima(hds.perf.physical.*.$System.CACHE.[0123456789]*.*.MP[BU]_UTILIZATION), 6, 7)"
    }
   ]
  },
  {
   "title": "Ports Top 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Port with highest IOPS on $System",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "target": "aliasByNode(highestMax(hds.perf.physical.*.$System.PORT.*.IOPS, 5), 6)"
      }
     ]
    },
    {
     "title": "Port with highest Throughput on $System",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "targets": [
      {
       "target": "aliasByNode(highestMax(hds.perf.physical.*.$System.PORT.*.TRANSFER, 5), 6)"
      }
     ]
    },
    {
     "title": "Port with highest Latency on $System",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "targets": [
      {
       "target": "aliasByNode(highestMax(hds.perf.physical.*.$System.PORT.*.LATENCY, 5), 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "LDEV Top 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDEV of $System with hight average IOPS",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.*.$System.LDEV.DP.*.*.IOPS, 5), 8)"
      }
     ]
    },
    {
     "title": "LDEV of $System with highest average Throughput",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.*.$System.LDEV.DP.*.*.TRANSFER, 5), 8)"
      }
     ]
    }
   ]
  },
  {
   "title": "HSD Top 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "HSD with highest average IOPS",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(grep(removeEmptySeries(sumSeriesWithWildcards(hds.perf.physical.*.$System.LU.*.*.*.IOPS, 8)), 'CL[1357]'), 5), 7)"
      }
     ]
    },
    {
     "title": "HSD with highest average IOPS",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(grep(removeEmptySeries(sumSeriesWithWildcards(hds.perf.physical.*.$System.LU.*.*.*.TRANSFER, 8)), 'CL[1357]'), 5), 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Utilization of all pools for: $System",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries(hds.capacity.*.$System.pool.*.capacity), 'Total Capacity')"
      },
      {
       "target": "alias(sumSeries(hds.capacity.*.$System.pool.*.used), 'Used Capacity')"
      }
     ]
    },
    {
     "title": "Pool with highest Usage Rate",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "target": "aliasByNode(highestCurrent(hds.capacity.*.$System.pool.*.percentused, 5), 5)"
      }
     ]
    }
   ]
  }
 ]
}