{
 "title": "HDS: Historical Pool Performance",
 "description": "Historical data based on Export Tool dump",
 "tags": [
  "HDS",
  "Historical"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.perf.physical.*" },
   { "name": "System", "query": "hds.perf.physical.$Type.*" },
   {
    "name": "Pool",
    "query": "hds.perf.physical.$Type.$System.LDEV.DP.*"
   }
  ]
 },
 "panels": [
  { "title": "Pool Performance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.*.IOPS, 8), 4, 7)"
    }
   ]
  },
  {
   "title": "Pool Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.*.TRANSFER, 8), 4, 7)"
    }
   ]
  },
  {
   "title": "Pool Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(averageSeriesWithWildcards(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.*.LATENCY, 8)), 4, 7)"
    }
   ]
  },
  {
   "title": "Top 5 LDEVs per Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "$System: LDEVs with highest average IOPS in pool: $Pool",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.*.IOPS, 5), 4, 7, 8)"
      }
     ]
    },
    {
     "title": "$System: LDEVs with highest maximum IOPS in pool: $Pool",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "target": "aliasByNode(highestMax(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.*.IOPS, 5), 4, 7, 8)"
      }
     ]
    }
   ]
  }
 ]
}