{
 "title": "HDS: Overview",
 "tags": [ "HDS" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.perf.physical.*" },
   { "name": "System", "query": "hds.perf.physical.$Type.*" }
  ]
 },
 "panels": [
  { "title": "System IOPS and Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total System IOPS for $System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.PORT.*.IOPS), '$System')"
    }
   ]
  },
  {
   "title": "Total System Throughput for $System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.PORT.*.TRANSFER), '$System')"
    }
   ]
  },
  { "title": "Cache Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "System Cache Write Pending: $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.CACHE.ALL.WRITE_PENDING, 4)"
    }
   ]
  },
  {
   "title": "System Cache Usage: $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.CACHE.ALL.UTILIZATION, 4)"
    }
   ]
  },
  { "title": "Multiprocessor Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average Multiprocessor Utilization: $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeriesWithWildcards(hds.perf.physical.$Type.$System.MP.*.UTIL, 6), 4)"
    }
   ]
  },
  {
   "title": "Top 5 Ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Port with highest average IOPS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.$Type.$System.PORT.*.IOPS, 5), 4, 6)"
      }
     ]
    },
    {
     "title": "Port with highest maximum IOPS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
     "targets": [
      {
       "target": "aliasByNode(highestMax(hds.perf.physical.$Type.$System.PORT.*.IOPS, 5), 4,6)"
      }
     ]
    },
    {
     "title": "Port with highest average Throughput",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.$Type.$System.PORT.*.TRANSFER, 5),4,6)"
      }
     ]
    },
    {
     "title": "Port with highest maximum Througput",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
     "targets": [
      {
       "target": "aliasByNode(highestMax(hds.perf.physical.$Type.$System.PORT.*.TRANSFER, 5),4,6)"
      }
     ]
    },
    {
     "title": "Port with highest average Latency",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.$Type.$System.PORT.*.LATENCY, 5), 4,6)"
      }
     ]
    },
    {
     "title": "Port with highest maximum Latency",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 38 },
     "targets": [
      {
       "target": "aliasByNode(highestMax(hds.perf.physical.$Type.$System.PORT.*.LATENCY, 5), 4, 6)"
      }
     ]
    }
   ]
  },
  { "title": "Lowest 10 Ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Port with lowest average IOPS",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "target": "aliasByNode(lowestAverage(hds.perf.physical.$Type.$System.PORT.*.IOPS, 10), 4, 6)"
    }
   ]
  },
  {
   "title": "Port with lowest average Throughput",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "target": "aliasByNode(lowestAverage(hds.perf.physical.$Type.$System.PORT.*.TRANSFER, 10), 4, 6)"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Storage Utilization of all pools for: $System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.pool.*.capacity), 'Total Capacity for $System')"
    },
    {
     "target": "alias(sumSeries(hds.capacity.$Type.$System.pool.*.used), 'Used Capacity for $System')"
    }
   ]
  },
  {
   "title": "Capacity Utilization",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(averageSeries(hds.capacity.$Type.$System.pool.*.percentavailable), 'Available Capacity')"
    },
    {
     "target": "alias(averageSeries(hds.capacity.$Type.$System.pool.*.percentused), 'Used Capacity')"
    }
   ]
  },
  {
   "title": "Pool with highest Usage Rate",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(hds.capacity.$Type.$System.pool.*.percentused, 5), 3, 5)"
    }
   ]
  }
 ]
}