{
 "title": "HDS: Realtime GAD Volume Overview",
 "tags": [
  "HDS",
  "REALTIME"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.perf.virtual.*" },
   { "name": "VSM", "query": "hds.perf.virtual.$Type.*" },
   {
    "name": "Pool",
    "query": "hds.perf.virtual.$Type.$VSM.LDEV.DP.*"
   },
   {
    "name": "VLDEV",
    "query": "hds.perf.virtual.$Type.$VSM.LDEV.DP.$Pool.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Virtual LDEV Read / Write IOPS for $VLDEV on $VSM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.virtual.$Type.$VSM.LDEV.DP.$Pool.$VLDEV.*.REALTIME_READ_IO_RATE, 9, 10)"
    },
    {
     "target": "aliasByNode(hds.perf.virtual.$Type.$VSM.LDEV.DP.$Pool.$VLDEV.*.REALTIME_WRITE_IO_RATE, 9, 10)"
    }
   ]
  },
  {
   "title": "Virtual LDEV Read / Write Transfer for $VLDEV on $VSM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.virtual.$Type.$VSM.LDEV.DP.$Pool.$VLDEV.*.REALTIME_READ_XFER_RATE, 9, 10)"
    },
    {
     "target": "aliasByNode(hds.perf.virtual.$Type.$VSM.LDEV.DP.$Pool.$VLDEV.*.REALTIME_WRITE_XFER_RATE, 9, 10)"
    }
   ]
  },
  {
   "title": "Virtual LDEV Read / Write Latency for $VLDEV on $VSM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.virtual.$Type.$VSM.LDEV.DP.$Pool.$VLDEV.*.REALTIME_READ_RESPONSE_RATE, 9, 10)"
    },
    {
     "target": "aliasByNode(hds.perf.virtual.$Type.$VSM.LDEV.DP.$Pool.$VLDEV.*.REALTIME_WRITE_RESPONSE_RATE, 9, 10)"
    }
   ]
  }
 ]
}