{
 "title": "HDS: Cache Details",
 "tags": [ "HDS" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.perf.physical.*" },
   { "name": "System", "query": "hds.perf.physical.$Type.*" },
   {
    "name": "CLPR",
    "query": "hds.perf.physical.$Type.$System.CACHE.*"
   }
  ]
 },
 "panels": [
  { "title": "Global Cache Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global Cache Write Pending Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.CACHE.ALL.WRITE_PENDING, 4)"
    }
   ]
  },
  {
   "title": "Global Cache Write Utilization Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.CACHE.ALL.UTILIZATION, 4)"
    }
   ]
  },
  {
   "title": "Cache Write Pending Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Write Pending by MP Board",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.$Type.$System.CACHE.$CLPR.*.MP[UB]_WRITE_PENDING, 4, 6, 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Modul Utilization (G1xx0 / VSP)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.$Type.$System.CACHE_MODUL.*.UTILIZATION, 4, 6)"
      }
     ]
    },
    {
     "title": "Cache Utilization by MP Board",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.$Type.$System.CACHE.$CLPR.*.MP[UB]_UTILIZATION, 4, 6)"
      }
     ]
    }
   ]
  }
 ]
}