{
 "title": "HDS: GAD VSM Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "VSM", "query": "hds.perf.virtual.*.*" },
   { "name": "Port", "query": "hds.perf.virtual.*.$VSM.LU.*" },
   {
    "name": "System",
    "query": "hds.perf.virtual.*.$VSM.LU.$Port.*.*.*"
   }
  ]
 },
 "panels": [
  { "title": "VSM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total amount of IOPS per Site for $VSM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.IOPS, 8), 8)"
    }
   ]
  },
  {
   "title": "Total transfer per Site for $VSM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.TRANSFER, 8), 8)"
    }
   ]
  },
  {
   "title": "VSM IO Read / Write Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read  I/O distribution for $VSM",
     "type": "graph",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.DP.000.*.*.READ_IOPS, 8), 8)"
      }
     ]
    },
    {
     "title": "Average Read I/O Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 3, "x": 11, "y": 11 },
     "format": "iops",
     "valueName": "avg",
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.READ_IOPS, 8), 8)"
      }
     ]
    },
    {
     "title": "Write I/O distribution for $VSM",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 11 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.DP.000.*.*.WRITE_IOPS, 8), 8)"
      }
     ]
    },
    {
     "title": "Average Write I/O Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 3, "x": 11, "y": 16 },
     "format": "iops",
     "valueName": "avg",
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.WRITE_IOPS, 8), 8)"
      }
     ]
    },
    {
     "title": "Read transfer distribution for $VSM",
     "type": "graph",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.DP.000.*.*.READ_TRANSFER, 8), 8)"
      }
     ]
    },
    {
     "title": "Average Read transfer Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 3, "x": 11, "y": 21 },
     "format": "KBs",
     "valueName": "avg",
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.READ_TRANSFER, 8), 8)"
      }
     ]
    },
    {
     "title": "Write transfer distribution for $VSM",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 21 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.DP.000.*.*.WRITE_TRANSFER, 8), 8)"
      }
     ]
    },
    {
     "title": "Average Write I/O Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 3, "x": 11, "y": 26 },
     "format": "KBs",
     "valueName": "avg",
     "targets": [
      {
       "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.WRITE_TRANSFER, 8), 8)"
      }
     ]
    }
   ]
  },
  {
   "title": "VSM Port Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Port IOPS for $VSM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.*.$System.PORT.$Port.IOPS, 4, 6)"
      }
     ]
    },
    {
     "title": "Port Transfer for $VSM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.*.$System.PORT.$Port.TRANSFER, 4, 6)"
      }
     ]
    },
    {
     "title": "Port Transfer for $VSM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(averageSeriesWithWildcards(hds.perf.physical.*.$System.PORT.$Port.LATENCY, 2, 2), 3, 5)"
      }
     ]
    }
   ]
  }
 ]
}