{
 "title": "HDS: Realtime GAD VSM Details",
 "tags": [
  "HDS",
  "REALTIME"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "VSM", "query": "hds.perf.virtual.*.*" },
   { "name": "Port", "query": "hds.perf.virtual.*.$VSM.LU.*" },
   {
    "name": "System",
    "query": "hds.perf.virtual.*.$VSM.LU.$Port.*.*.*"
   }
  ]
 },
 "panels": [
  { "title": "VSM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total amount of IOPS per Site for $VSM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.REALT*_IO_RATE, 8, 10), 8)"
    }
   ]
  },
  {
   "title": "Total transfer per Site for $VSM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.REALT*_XFER_RATE, 8, 10), 8)"
    }
   ]
  },
  { "title": "VSM IO Read / Write Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Read  I/O distribution for $VSM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.DP.000.*.*.REALTIME_READ_IO_RATE, 8), 8)"
    }
   ]
  },
  {
   "title": "Current Read I/O Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 11 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.REALTIME_READ_IO_RATE, 8), 8)"
    }
   ]
  },
  {
   "title": "Write I/O distribution for $VSM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.DP.000.*.*.REALTIME_WRITE_IO_RATE, 8), 8)"
    }
   ]
  },
  {
   "title": "Current Write I/O Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 16 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.REALTIME_WRITE_IO_RATE, 8), 8)"
    }
   ]
  },
  {
   "title": "Read transfer distribution for $VSM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.DP.000.*.*.REALTIME_READ_XFER_RATE, 8), 8)"
    }
   ]
  },
  {
   "title": "Current Read transfer Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 21 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.REALTIME_READ_XFER_RATE, 8), 8)"
    }
   ]
  },
  {
   "title": "Write transfer distribution for $VSM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.DP.000.*.*.REALTIME_WRITE_XFER_RATE, 8), 8)"
    }
   ]
  },
  {
   "title": "Average Write Transfer Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 26 },
   "format": "KBs",
   "valueName": "avg",
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.WRITE_TRANSFER, 8), 8)"
    }
   ]
  },
  {
   "title": "VSM Port Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Port IOPS for $VSM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.*.$System.PORT.$Port.IOPS, 4, 6)"
      }
     ]
    },
    {
     "title": "Port Transfer for $VSM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.*.$System.PORT.$Port.TRANSFER, 4, 6)"
      }
     ]
    },
    {
     "title": "Port Transfer for $VSM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(averageSeriesWithWildcards(hds.perf.physical.*.$System.PORT.$Port.LATENCY, 2, 2), 3, 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "LDEV Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 LDEV with highest avg IOPS",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.REALTIME_*IO_RATE, 9, 10), 10), 8)"
      }
     ]
    },
    {
     "title": "Top 10 LDEV with highest avg Throughput",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(sumSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.REALTIM*XFER_RATE, 9, 10), 10), 8)"
      }
     ]
    },
    {
     "title": "Top 10 LDEV with highest avg Throughput",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "target": "aliasByNode(averageSeriesWithWildcards(hds.perf.virtual.*.$VSM.LDEV.*.*.*.*.REALTIME_*RESPONSE_RATE, 9, 10), 8)"
      }
     ]
    }
   ]
  }
 ]
}