{
 "title": "HDS: Realtime System Performance",
 "tags": [
  "HDS",
  "REALTIME"
 ],
 "time": { "from": "now-6h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "System", "query": "hds.perf.physical.*.*" }
  ]
 },
 "panels": [
  { "title": "System IOPS and Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total System IOPS for $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.*.$System.PORT.*.REALTIME_AVG_IO_RATE), '$System')"
    }
   ]
  },
  {
   "title": "Total System Throughput for $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.*.$System.PORT.*.REALTIME_AVG_XFER_RATE), '$System')"
    }
   ]
  },
  {
   "title": "READ / WRITE IOPS for $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "alias(hds.perf.physical.*.$System.SYSTEM.LDA.REALTIME_READ_IO_RATE, 'READ_IO_RATE')"
    },
    {
     "target": "alias(hds.perf.physical.*.$System.SYSTEM.LDA.REALTIME_WRITE_IO_RATE, 'WRITE_IO_RATE')"
    }
   ]
  },
  {
   "title": "READ/WRITE IO Ratio for $System",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(hds.perf.physical.*.$System.SYSTEM.LDA.REALTIME_READ_IO_RATE, 'READ_IO_RATE')"
    },
    {
     "target": "alias(hds.perf.physical.*.$System.SYSTEM.LDA.REALTIME_WRITE_IO_RATE, 'WRITE_IO_RATE')"
    }
   ]
  },
  {
   "title": "READ / WRITE Throughput for $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "alias(hds.perf.physical.*.$System.SYSTEM.LDA.REALTIME_READ_XFER_RATE, 'READ_IO_RATE')"
    },
    {
     "target": "alias(hds.perf.physical.*.$System.SYSTEM.LDA.REALTIME_WRITE_XFER_RATE, 'WRITE_IO_RATE')"
    }
   ]
  },
  {
   "title": "READ/WRITE Throughput Ratio for $System",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(hds.perf.physical.*.$System.SYSTEM.LDA.REALTIME_READ_XFER_RATE, 'READ_IO_RATE')"
    },
    {
     "target": "alias(hds.perf.physical.*.$System.SYSTEM.LDA.REALTIME_WRITE_XFER_RATE, 'WRITE_IO_RATE')"
    }
   ]
  },
  {
   "title": "Multiprocessor Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Multiprocessor Utilization: $System",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.PRCS.*._Total.REALTIME_PROCESSOR_BUSY_RATE), 6)"
      }
     ]
    },
    {
     "title": "Current Global Mutliprocessor Utilization $System",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 4, "x": 10, "y": 22 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "target": "averageSeries(hds.perf.physical.*.$System.PRCS.*._Total.REALTIME_PROCESSOR_BUSY_RATE)"
      }
     ]
    },
    {
     "title": "Max Multiprocessor Buffer Length: $System",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.PRCS.*._Total.REALTIME_MAX_BUFFER_IO_COUNT), 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Cache Write Pending: $System",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(sortByMaxima(hds.perf.physical.*.$System.CACHE.ALL.REALTIME_CACHE_WRITE_PENDING_RATE))"
      }
     ]
    },
    {
     "title": "Current Global Cache Write Pending $System",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 8, "y": 32 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "target": "hds.perf.physical.*.$System.CACHE.ALL.REALTIME_CACHE_WRITE_PENDING_RATE"
      }
     ]
    },
    {
     "title": "Current Global Cache Utiliation $System",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 12, "y": 32 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "target": "hds.perf.physical.*.$System.CACHE.ALL.REALTIME_MAX_CACHE_MEMORY_USAGE_RATE"
      }
     ]
    },
    {
     "title": "System Cache Usage: $System",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(sortByMinima(hds.perf.physical.*.$System.CACHE.ALL.REALTIME_CACHE_MEMORY_USAGE_RATE))"
      }
     ]
    }
   ]
  },
  {
   "title": "Channel Adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Channel Adapter IOPS of $System",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.*.$System.CHS.*.REALTIME_AVG_IO_RATE, 6)"
      }
     ]
    },
    {
     "title": "Channel Adapter Through of $System",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.*.$System.CHS.*.REALTIME_AVG_XFER_RATE, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "RAID Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max. Parity Group Utilization for $System",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(hds.perf.physical.*.$System.RGS.*.REALTIME_MAX_BUSY_RATE, 6)"
      }
     ]
    },
    {
     "title": "Current Average RAID Group Utilization",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 44 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "target": "averageSeries(hds.perf.physical.*.$System.RGS.*.REALTIME_MAX_BUSY_RATE)"
      }
     ]
    },
    {
     "title": "Distribution of RAID Group Busy for $System",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 44 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.RGS.*.REALTIME_MAX_BUSY_RATE), 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Port Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Realtime Port Throughput for $System",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.PORT.*.REALTIME_AVG_XFER_RATE), 6)"
      }
     ]
    },
    {
     "title": "Realtime Port Throughput for $System",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.PORT.*.REALTIME_AVG_IO_RATE), 6)"
      }
     ]
    },
    {
     "title": "Port with highest IOPS on $System",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "targets": [
      {
       "target": "aliasByNode(highestCurrent(hds.perf.physical.*.$System.PORT.*.REALTIME_AVG_IO_RATE, 20), 6)"
      }
     ]
    },
    {
     "title": "Port with highest Throughput on $System",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "targets": [
      {
       "target": "aliasByNode(highestCurrent(hds.perf.physical.*.$System.PORT.*.REALTIME_AVG_XFER_RATE, 20), 6)"
      }
     ]
    },
    {
     "title": "Port with highest Latency on $System",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "targets": [
      {
       "target": "aliasByNode(highestCurrent(hds.perf.physical.*.$System.PORT.*.LATENCY, 20), 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "LDEV Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDEV of $System with hight average IOPS",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "target": "aliasByNode(highestCurrent(sumSeriesWithWildcards(hds.perf.physical.*.$System.LDEV.DP.000.*.REAL*IO_RATE, 9), 20), 8)"
      }
     ]
    },
    {
     "title": "LDEV of $System with hight average Throughput",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "target": "aliasByNode(highestCurrent(sumSeriesWithWildcards(hds.perf.physical.*.$System.LDEV.DP.*.*.REALTIME_*_XFER_RATE, 9), 20), 8)"
      }
     ]
    }
   ]
  }
 ]
}