{
 "title": "HDS: System Remote Copy Details",
 "tags": [ "HDS" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.perf.physical.*" },
   { "name": "System", "query": "hds.perf.physical.$Type.*" }
  ]
 },
 "panels": [
  { "title": "Remote Copy Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RIO Operations for $System",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.RC.Initial_Copy_RIO, 4, 6)"
    },
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.RC.All_RIO, 4, 6)"
    },
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.RC.Update_Copy_RIO, 4, 6)"
    }
   ]
  },
  {
   "title": "RIO Response Time for $System",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.RC.Initial_Copy_Response, 4, 6)"
    },
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.RC.Update_Copy_Response, 4, 6)"
    }
   ]
  },
  {
   "title": "Inital vs. Update Copy Transfer for $System",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.RC.Initial_Copy_Transfer, 4, 6)"
    },
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.RC.Update_Copy_Transfer, 4, 6)"
    }
   ]
  },
  { "title": "Remote Copy Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "The percentage of completion of copy operations for $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.RC.Pair_Synchronized, 4)"
    }
   ]
  },
  {
   "title": "Number of Out of Sync Tracks for $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.RC.Out_of_Sync_Tracks, 4)"
    }
   ]
  },
  {
   "title": "Number of RIO Errors for $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.RC.RIO_Error, 4)"
    }
   ]
  }
 ]
}