{
 "title": "HDS: System Performance",
 "tags": [ "HDS" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "System", "query": "hds.perf.physical.*.*" }
  ]
 },
 "panels": [
  { "title": "System IOPS and Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total System IOPS for $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.*.$System.PORT.*.IOPS), '$System')"
    }
   ]
  },
  {
   "title": "Total System Throughput for $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.*.$System.PORT.*.TRANSFER), '$System')"
    }
   ]
  },
  { "title": "Multiprocessor Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average Multiprocessor Utilization: $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.MP.*.UTIL), 6)"
    }
   ]
  },
  {
   "title": "Global Mutliprocessor Utilization $System",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(hds.perf.physical.*.$System.MP.*.UTIL)"
    }
   ]
  },
  { "title": "Cache Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "System Cache Write Pending: $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.CACHE.[0123456789]*.*.MP[BU]_WRITE_PENDING), 6, 7)"
    }
   ]
  },
  {
   "title": "Global Cache Write Pending $System",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 23 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "hds.perf.physical.*.$System.CACHE.ALL.WRITE_PENDING"
    }
   ]
  },
  {
   "title": "Global Cache Utiliation $System",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "hds.perf.physical.*.$System.CACHE.ALL.UTILIZATION"
    }
   ]
  },
  {
   "title": "System Cache Usage: $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMinima(hds.perf.physical.*.$System.CACHE.[0123456789]*.*.MP[BU]_UTILIZATION), 6, 7)"
    }
   ]
  },
  {
   "title": "Disk Adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Adapter Utilization",
     "type": "graph",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.DKA.*.UTILIZATION), 6)"
      }
     ]
    },
    {
     "title": "Global Average Disk Adapter Utilization $System",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 34 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "target": "averageSeriesWithWildcards(hds.perf.physical.*.$System.DKA.*.UTILIZATION, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Channel Adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Channel Adapter Utilization",
     "type": "graph",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(hds.perf.physical.*.$System.CHA.*.UTILIZATION), 6)"
      }
     ]
    },
    {
     "title": "Global Average Channel Adapter Utilization $System",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 35 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "target": "averageSeriesWithWildcards(hds.perf.physical.*.$System.CHA.*.UTILIZATION, 6)"
      }
     ]
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Storage Utilization of all pools for: $System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.capacity.*.$System.pool.*.capacity), 'Total Capacity')"
    },
    {
     "target": "alias(sumSeries(hds.capacity.*.$System.pool.*.used), 'Used Capacity')"
    }
   ]
  },
  {
   "title": "Pool with highest Usage Rate",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "target": "aliasByNode(highestCurrent(hds.capacity.*.$System.pool.*.percentused, 5), 5)"
    }
   ]
  },
  {
   "title": "Port Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Port with highest IOPS on $System",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(highestMax(hds.perf.physical.*.$System.PORT.*.IOPS, 20)), 6)"
      }
     ]
    },
    {
     "title": "Port with highest Throughput on $System",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(highestMax(hds.perf.physical.*.$System.PORT.*.TRANSFER, 20)), 6)"
      }
     ]
    },
    {
     "title": "Port with highest Latency on $System",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(highestMax(hds.perf.physical.*.$System.PORT.*.LATENCY, 20)), 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "LDEV Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDEV of $System with hight average IOPS",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.*.$System.LDEV.DP.*.*.IOPS, 10), 8)"
      }
     ]
    },
    {
     "title": "LDEV of $System with hight average Throughput",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(hds.perf.physical.*.$System.LDEV.DP.*.*.TRANSFER, 10), 8)"
      }
     ]
    }
   ]
  },
  {
   "title": "HSD Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 HSDs für $System",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(grep(removeEmptySeries(sumSeriesWithWildcards(hds.perf.physical.*.$System.LU.*.*.*.IOPS, 8)), 'CL[1357]'), 10), 7)"
      }
     ]
    },
    {
     "title": "Top 10 HSDs für $System",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(grep(removeEmptySeries(sumSeriesWithWildcards(hds.perf.physical.*.$System.LU.*.*.*.TRANSFER, 8)), 'CL[1357]'), 10), 7)"
      }
     ]
    }
   ]
  }
 ]
}