{
 "title": "HDS: LDEV Details",
 "tags": [ "HDS" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "query": "hds.perf.physical.*" },
   { "name": "System", "query": "hds.perf.physical.$Type.*" },
   {
    "name": "Pool",
    "query": "hds.perf.physical.$Type.$System.LDEV.DP.*"
   },
   {
    "name": "LDEV",
    "query": "hds.perf.physical.$Type.$System.LDEV.DP.$Pool.*"
   }
  ]
 },
 "panels": [
  { "title": "LDEV Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LDEV IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.IOPS, 8)"
    }
   ]
  },
  {
   "title": "LDEV Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.TRANSFER, 8)"
    }
   ]
  },
  {
   "title": "LDEV Latency $LDEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.LATENCY, 8)"
    }
   ]
  },
  { "title": "Read / Write Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Read & Write IOPS for $LDEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_IOPS)"
    },
    {
     "target": "aliasByMetric(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_IOPS)"
    }
   ]
  },
  {
   "title": "Read & Write Ratio on IOPS for $LDEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_IOPS, #B), 'Read Percentage')",
     "targetFull": "alias(asPercent(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_IOPS, hds.perf.$Type.$System.LDEV.DP.$Pool.$LDEV.IOPS), 'Read Percentage')"
    },
    {
     "target": "alias(asPercent(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_IOPS, #B), 'Write Percentage')",
     "targetFull": "alias(asPercent(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_IOPS, hds.perf.$Type.$System.LDEV.DP.$Pool.$LDEV.IOPS), 'Write Percentage')"
    }
   ]
  },
  {
   "title": "Read / Write IO Ratio for LDEV $LDEV",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(averageSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_IOPS), 'READ IOPS')"
    },
    {
     "target": "alias(averageSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_IOPS), 'WRITE IOPS')"
    }
   ]
  },
  {
   "title": "Read & Write Throughput for $LDEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_TRANSFER)"
    },
    {
     "target": "aliasByMetric(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_TRANSFER)"
    }
   ]
  },
  {
   "title": "Read & Write Ratio on Throughput for $LDEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_TRANSFER, #B), 'Read Percentage')",
     "targetFull": "alias(asPercent(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_TRANSFER, hds.perf.$Type.$System.LDEV.DP.$Pool.$LDEV.TRANSFER), 'Read Percentage')"
    },
    {
     "target": "alias(asPercent(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_TRANSFER, #B), 'Write Percentage')",
     "targetFull": "alias(asPercent(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_TRANSFER, hds.perf.$Type.$System.LDEV.DP.$Pool.$LDEV.TRANSFER), 'Write Percentage')"
    }
   ]
  },
  {
   "title": "Read / Write Throughput Ratio for LDEV $LDEV",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(averageSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_TRANSFER), 'READ TRANSFER')"
    },
    {
     "target": "alias(averageSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_TRANSFER), 'WRITE TRANSFER')"
    }
   ]
  },
  {
   "title": "Average Read & Write IO Size for $LDEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_TRANSFER, #A), 'Write Blocksize')",
     "targetFull": "alias(divideSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_TRANSFER, hds.perf.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_TRANSFER), 'Write Blocksize')"
    },
    {
     "target": "alias(divideSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_TRANSFER, #B), 'Read Blocksize')",
     "targetFull": "alias(divideSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_TRANSFER, hds.perf.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_TRANSFER), 'Read Blocksize')"
    }
   ]
  },
  {
   "title": "Average Write IO Size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 23 },
   "format": "kbytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "divideSeries(averageSeries(hds.perf.physical.$Type.$System.LDEV.*.*.$LDEV.WRITE_TRANSFER), #A)",
     "targetFull": "divideSeries(averageSeries(hds.perf.physical.$Type.$System.LDEV.*.*.$LDEV.WRITE_TRANSFER), averageSeries(hds.perf.$Type.$System.LDEV.*.*.$LDEV.WRITE_IOPS))"
    }
   ]
  },
  {
   "title": "Average Read IO Size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 23 },
   "format": "kbytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "divideSeries(averageSeries(hds.perf.physical.$Type.$System.LDEV.*.*.$LDEV.READ_TRANSFER), #A)",
     "targetFull": "divideSeries(averageSeries(hds.perf.physical.$Type.$System.LDEV.*.*.$LDEV.READ_TRANSFER), averageSeries(hds.perf.$Type.$System.LDEV.*.*.$LDEV.READ_IOPS))"
    }
   ]
  },
  {
   "title": "Average  Write IO Size Histogram for $LDEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_TRANSFER, #A), 'Write Blocksize')",
     "targetFull": "alias(divideSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_TRANSFER, hds.perf.$Type.$System.LDEV.DP.$Pool.$LDEV.WRITE_TRANSFER), 'Write Blocksize')"
    }
   ]
  },
  {
   "title": "Average  Read IO Size Histogram for $LDEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_TRANSFER, #A), 'Write Blocksize')",
     "targetFull": "alias(divideSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_TRANSFER, hds.perf.$Type.$System.LDEV.DP.$Pool.$LDEV.READ_IOPS), 'Write Blocksize')"
    }
   ]
  },
  { "title": "Sequential / Random Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Random & Sequential IOPS for LDEV $LDEV",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.RND_*_IOPS), 'RANDOM IOPS')"
    },
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.SEQ_*_IOPS), 'SEQUENTIAL IOPS')"
    }
   ]
  },
  {
   "title": "Random & Seqution IOPS for LDEV $LDEV",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.RND_*_IOPS), 'RANDOM IOPS')"
    },
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.SEQ_*_IOPS), 'SEQUENTIAL IOPS')"
    }
   ]
  },
  {
   "title": "Random & Sequential READ IOPS for LDEV $LDEV",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.RND_READ_IOPS), 'RANDOM READ IOPS')"
    },
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.SEQ_READ_IOPS), 'SEQUENTIAL READ IOPS')"
    }
   ]
  },
  {
   "title": "Random & Seqution READ IOPS for LDEV $LDEV",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 47 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.RND_READ_IOPS), 'RANDOM READ IOPS')"
    },
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.SEQ_READ_IOPS), 'SEQUENTIAL READ IOPS')"
    }
   ]
  },
  {
   "title": "Random & Sequential WRITE IOPS for LDEV $LDEV",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.RND_WRITE_IOPS), 'RANDOM WRITE IOPS')"
    },
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.SEQ_WRITE_IOPS), 'SEQUENTIAL WRITE IOPS')"
    }
   ]
  },
  {
   "title": "Random & Seqution WRITE IOPS for LDEV $LDEV",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 47 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.RND_WRITE_IOPS), 'RANDOM WRITE IOPS')"
    },
    {
     "target": "alias(sumSeries(hds.perf.physical.$Type.$System.LDEV.DP.$Pool.$LDEV.SEQ_WRITE_IOPS), 'SEQUENTIAL WRITE IOPS')"
    }
   ]
  },
  { "title": "LDEV Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "LDEV Capacity and Used for $LDEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(hds.capacity.$Type.$System.ldev.DP.$Pool.$LDEV.capacity)"
    },
    {
     "target": "aliasByMetric(hds.capacity.$Type.$System.ldev.DP.$Pool.$LDEV.used)"
    }
   ]
  },
  {
   "title": "Tier Utilization for LDEV: $LDEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(hds.capacity.$Type.$System.ldev.DP.$Pool.$LDEV.tier3)"
    },
    {
     "target": "aliasByMetric(hds.capacity.$Type.$System.ldev.DP.$Pool.$LDEV.tier2)"
    },
    {
     "target": "aliasByMetric(hds.capacity.$Type.$System.ldev.DP.$Pool.$LDEV.tier1)"
    }
   ]
  }
 ]
}