{
 "title": "HV: Historical Port Details",
 "description": "FrontEnd Ports - Historical data based on Export Tool dump",
 "tags": [
  "Hitachi Vantara",
  "Historical"
 ],
 "time": { "from": "now-6h", "to": "now-1h" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\"},storagetype)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\",storagetype=~\"$Type\"},storagename)"
    }
   },
   {
    "name": "Port",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\",storagetype=~\"$Type\",storagename=~\"$System\"},item)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Port Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Port IOPS for $Port on $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sort_desc(hv_port_iops{storagetype=~\"$Type\", storagename=~\"$System\", item=~\"$Port\"})",
     "legendFormat": "{{storagename}}/{{item}}"
    }
   ]
  },
  {
   "title": "Port IOPS for $Port on $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sort_desc(hv_port_transfer{storagetype=~\"$Type\", storagename=~\"$System\", item=~\"$Port\"})",
     "legendFormat": "{{storagename}}/{{item}}"
    }
   ]
  },
  {
   "title": "Port IOPS for $Port on $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sort_desc(hv_port_latency{storagetype=~\"$Type\", storagename=~\"$System\", item=~\"$Port\"})",
     "legendFormat": "{{storagename}}/{{item}}"
    }
   ]
  },
  {
   "title": "Port Performance (stacked)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Port IOPS for $Port on $System",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sort_desc(hv_port_iops{storagetype=~\"$Type\", storagename=~\"$System\", item=~\"$Port\"})",
       "legendFormat": "{{storagename}}/{{item}}"
      }
     ]
    },
    {
     "title": "Port IOPS for $Port on $System",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sort_desc(hv_port_transfer{storagetype=~\"$Type\", storagename=~\"$System\", item=~\"$Port\"})",
       "legendFormat": "{{storagename}}/{{item}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HSD Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Port: IOPS by Host Storage Domains",
     "type": "timeseries",
     "description": "Sums up all the IOPS of the LUNs in a HSD for EACH port select. Number might be much higher then real numbers since the IO is counted for each path one time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(hsd) (hv_lu_iops{entity=\"physical\", port=~\"$Port\", storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{HSD}}"
      }
     ]
    },
    {
     "title": "$Port: Throughput by Host Storage Domains",
     "type": "timeseries",
     "description": "Sums up all the throughput of the LUNs in a HSD for EACH port select. Number might be much higher then real numbers since the IO is counted for each path one time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(hsd) (hv_lu_read_transfer{entity=\"physical\", port=~\"$Port\", storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{HSD}}"
      }
     ]
    }
   ]
  },
  { "title": "Top LUs on Port $Port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Top LUs on Port $Port by IOPS",
   "type": "table",
   "description": "Top5\nPanel uses VictoriaMetrics function",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk_max(5,avg(hv_lu_iops{storagetype=~\"$Type\", storagename=~\"$System\", port=~\"$Port\"}) by (storagename,hsd,lu,ldev))",
     "legendFormat": "{{storagename}} - {{hsd}} - {{lu}} ({{ldev}})"
    }
   ]
  },
  {
   "title": "Top LUs on Port $Port by Throughput",
   "type": "table",
   "description": "Top5\nPanel uses VictoriaMetrics function",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "topk_max(5,avg(hv_lu_transfer{storagetype=~\"$Type\", storagename=~\"$System\", port=~\"$Port\"}) by (storagename,hsd,lu,ldev))",
     "legendFormat": "{{storagename}} - {{hsd}} - {{lu}} ({{ldev}})"
    }
   ]
  },
  {
   "title": "Top LUs on Port $Port by Latency",
   "type": "table",
   "description": "Top5\nPanel uses VictoriaMetrics function",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk_max(5,avg(hv_lu_latency{storagetype=~\"$Type\", storagename=~\"$System\", port=~\"$Port\"}) by (storagename,hsd,lu,ldev))",
     "legendFormat": "{{storagename}} - {{hsd}} - {{lu}} ({{ldev}})"
    }
   ]
  }
 ]
}