{
 "title": "HV: Historical Cache Details",
 "description": "Historical data based on Export Tool dump",
 "tags": [
  "Hitachi Vantara",
  "Historical"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_cache_utilization{entity=\"physical\"},storagetype)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_cache_utilization{entity=\"physical\",storagetype=\"$Type\"},storagename)"
    }
   },
   {
    "name": "CLPR",
    "query": {
     "query": "label_values(hv_cache_mpu_utilization{entity=\"physical\", storagetype=~\"$Type\", storagename=~\"$System\"},item)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global Cache Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global Cache Write Pending Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hv_cache_write_pending{item=\"ALL\", storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Global Cache Write Utilization Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hv_cache_utilization{item=\"ALL\", storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  { "title": "Cache Write Pending Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Cache Write Pending by MP Board",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hv_cache_mpu_write_pending{item=~\"$CLPR\", storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}} - {{item}}"
    }
   ]
  },
  { "title": "Cache Utilization Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Cache Modul Utilization (G1xx0 / VSP)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hv_cache_modul_utilization{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}} - {{item}}"
    }
   ]
  },
  {
   "title": "Cache Utilization by MP Board",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hv_cache_mpu_utilization{storagetype=~\"$Type\", storagename=~\"$System\", item=~\"$CLPR\"}",
     "legendFormat": "{{storagename}} - {{item}}"
    }
   ]
  }
 ]
}