{
 "title": "HV: Historical Pool Statistics",
 "description": "Historical data based on ExportTool dump",
 "tags": [
  "Hitachi Vantara",
  "Historical"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\"},storagetype)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\",storagetype=~\"$Type\"},storagename)"
    }
   },
   {
    "name": "Pool",
    "query": {
     "query": "label_values(hv_ldev_iops{entity=\"physical\",storagetype=~\"$Type\",storagename=~\"$System\"},p_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Volume Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume count for $System and Pools: $Pool",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hv_capacity_pool_volumecount{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\"}",
     "legendFormat": "{{storagename}} - $Pool"
    }
   ]
  },
  {
   "title": "Volume Count over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(poolid) (hv_capacity_pool_volumecount{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\"})",
     "legendFormat": "Vol count for $System and Pools: $Pool"
    }
   ]
  },
  {
   "title": "Volume Count over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(poolid) (hv_capacity_pool_volumecount{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\"})",
     "legendFormat": "Vol count for $System and Pools: $Pool"
    }
   ]
  },
  { "title": "Pool Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pool Total Capacity for $System Pool: $Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hv_capacity_pool_total{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\"}",
     "legendFormat": "{{storagename}} - {{poolid}}"
    }
   ]
  },
  {
   "title": "Pool Used Capacity for $System Pool: $Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hv_capacity_pool_used{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\"}",
     "legendFormat": "{{storagename}} - {{poolid}}"
    }
   ]
  },
  { "title": "Tier Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Tier Usage for $System Pool: $Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum by(poolid) (hv_capacity_ldev_tier1{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\", ldevtype=\"DP\"})",
     "legendFormat": "Tier 1"
    },
    {
     "expr": "sum by(poolid) (hv_capacity_ldev_tier2{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\", ldevtype=\"DP\"})",
     "legendFormat": "Tier 2"
    },
    {
     "expr": "sum by(poolid) (hv_capacity_ldev_tier3{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\", ldevtype=\"DP\"})",
     "legendFormat": "Tier 3"
    }
   ]
  },
  {
   "title": "Tier Usage for $System Pool: $Pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(poolid) (hv_capacity_ldev_tier1{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\", ldevtype=\"DP\"})",
     "legendFormat": "Tier 1"
    },
    {
     "expr": "sum by(poolid) (hv_capacity_ldev_tier2{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\", ldevtype=\"DP\"})",
     "legendFormat": "Tier 2"
    },
    {
     "expr": "sum by(poolid) (hv_capacity_ldev_tier3{poolid=~\"$Pool\", storagename=\"$System\", storagetype=\"$Type\", ldevtype=\"DP\"})",
     "legendFormat": "Tier 3"
    }
   ]
  }
 ]
}