{
 "title": "HV: Historical GAD VSM Details",
 "description": "Global Active Device - Virtual Storage Machine Details - Historical data based on Export Tool dump",
 "tags": [
  "Hitachi Vantara",
  "Historical"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VSM",
    "query": {
     "query": "label_values(hv_ldev_iops{entity=\"virtual\"},storagename)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_ldev_iops{entity=\"virtual\",storagename=\"$VSM\"},physicalstoragename)"
    }
   },
   {
    "name": "Port",
    "query": {
     "query": "label_values(hv_ldev_iops{entity=\"virtual\"},storagename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "VSM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total amount of IOPS per Site for $VSM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(physicalstoragename) (hv_ldev_iops{entity=\"virtual\", storagename=\"DFVFVSP01_02\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Transfer per Site for $VSM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by(physicalstoragename) (hv_ldev_read_transfer{entity=\"virtual\", storagename=\"DFVFVSP01_02\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "VSM Read / Write Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read  I/O distribution for $VSM",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(physicalstoragename) (hv_ldev_read_iops{entity=\"virtual\", storagename=\"$VSM\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Read  I/O distribution for $VSM",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by(physicalstoragename) (hv_ldev_read_iops{entity=\"virtual\", storagename=\"$VSM\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Write I/O distribution for $VSM",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(physicalstoragename) (hv_ldev_write_iops{entity=\"virtual\", storagename=\"$VSM\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Write  I/O distribution for $VSM",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by(physicalstoragename) (hv_ldev_write_iops{entity=\"virtual\", storagename=\"$VSM\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Read Transfer distribution for $VSM",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(physicalstoragename) (hv_ldev_read_transfer{entity=\"virtual\", storagename=\"$VSM\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Read Transfer distribution for $VSM",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 10, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by(physicalstoragename) (hv_ldev_read_transfer{entity=\"virtual\", storagename=\"$VSM\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Write Transfer distribution for $VSM",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(physicalstoragename) (hv_ldev_write_transfer{entity=\"virtual\", storagename=\"$VSM\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Write Transfer distribution for $VSM",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 10, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by(physicalstoragename) (hv_ldev_write_transfer{entity=\"virtual\", storagename=\"$VSM\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "VSM Port Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  }
 ]
}