{
 "title": "HV: hds2graphite Statistics",
 "description": "Runtime statistics for the hds2graphite tool",
 "tags": [
  "Hitachi Vantara",
  "hds2graphite"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_runtime_total,storagetype)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_runtime_total{storagetype=~\"$Type\"},storagename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Statistic Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Runtime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hv_runtime_total{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Total Metrics collected",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(storagename) ({__name__=~\"hv_metriccount.*\", storagetype=~\"$Type\", storagename=~\"$System\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RAIDCOM Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Query for DP Pools",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hv_runtime_getdppools{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Query for Parity Groups",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hv_runtime_getpgs{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Query for DP-Vols",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hv_runtime_getdpldev{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Query for PG-Vols",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hv_runtime_getpgldev{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  { "title": "Export Tool Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Export Tool Runtime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hv_runtime_exporttool{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  { "title": "Send to VictoriaMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Import Performance Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hv_runtime_importmetric{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Import Pool Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hv_runtime_logpoolstats{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Import LDEV Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hv_runtime_logldevstats{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Import Logical Unit Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hv_runtime_loglustats{storagetype=~\"$Type\", storagename=~\"$System\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  }
 ]
}