{
 "title": "HV: Historical Remote Copy Details",
 "description": "Historical data based on Export Tool dump",
 "tags": [
  "Hitachi Vantara",
  "Historical"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\"},storagetype)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\",storagetype=~\"$Type\"},storagename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Remote Copy Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total RIO for $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "hv_rc_initial_copy_rio{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}} Initial_Copy"
    },
    {
     "expr": "hv_rc_all_rio{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}} All"
    },
    {
     "expr": "hv_rc_update_copy_rio{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}} Update_Copy"
    }
   ]
  },
  {
   "title": "RIO Response Time for $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hv_rc_initial_copy_response{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}} Initial_Copy"
    },
    {
     "expr": "hv_rc_update_copy_response{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}} Update_Copy"
    }
   ]
  },
  {
   "title": "RIO Transfer for $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "hv_rc_initial_copy_transfer{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}} Initial_Copy"
    },
    {
     "expr": "hv_rc_update_copy_transfer{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}} Update_Copy"
    }
   ]
  },
  { "title": "Remote Copy Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "The percentage of completion of copy operations for $System",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hv_rc_pair_synchronized{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Number of Out of Sync Tracks for $System",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hv_rc_out_of_sync_tracks{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Number of RIO Errors for $System",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hv_rc_rio_error{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  }
 ]
}