{
 "title": "HV: Historical System Performance",
 "description": "Historical data based on Export Tool dump",
 "tags": [
  "Hitachi Vantara",
  "Historical"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\"},storagetype)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\",storagetype=~\"$Type\"},storagename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System IOPS and Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total System IOPS for $System",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(hv_port_iops{storagename=~\"$System\", storagetype=~\"$Type\"})",
     "legendFormat": "$System"
    }
   ]
  },
  {
   "title": "Total System Throughput for $System",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(hv_port_transfer{storagename=~\"$System\", storagetype=~\"$Type\"})",
     "legendFormat": "$System"
    }
   ]
  },
  { "title": "Multiprocessor Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Avergage Multiprocessor Utilization: $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_desc(hv_mp_util{storagetype=~\"$Type\", storagename=~\"$System\"})",
     "legendFormat": "{{storagename}}/{{item}}"
    }
   ]
  },
  {
   "title": "Global Multiprocessor Utilization: $System",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(hv_mp_util{storagetype=~\"$Type\", storagename=~\"$System\"})",
     "legendFormat": "{{storagename}}/{{item}}"
    }
   ]
  },
  { "title": "Cache Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "System Cache Write Pending: $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hv_cache_mpu_write_pending{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}} {{item}}"
    }
   ]
  },
  {
   "title": "Global Cache Write Pending: $System",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hv_cache_write_pending{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "Global Cache Utiliation: $System",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hv_cache_utilization{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}}"
    }
   ]
  },
  {
   "title": "System Cache Usage: $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hv_cache_mpu_utilization{storagename=~\"$System\", storagetype=~\"$Type\"}",
     "legendFormat": "{{storagename}} {{item}}"
    }
   ]
  },
  {
   "title": "Ports Top 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Port with highest average IOPS",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk_avg(5, hv_port_iops{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{item}}"
      }
     ]
    },
    {
     "title": "Port with highest average Throughput",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "topk_avg(5, hv_port_transfer{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{item}}"
      }
     ]
    },
    {
     "title": "Port with highest average Latency",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk_avg(5, hv_port_latency{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{item}}"
      }
     ]
    },
    {
     "title": "Port with highest maximum IOPS",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk_max(5, hv_port_iops{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{item}}"
      }
     ]
    },
    {
     "title": "Port with highest maximum Throughput",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "topk_max(5, hv_port_transfer{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{item}}"
      }
     ]
    },
    {
     "title": "Port with highest maximum Latency",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk_max(5, hv_port_latency{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{item}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LDEV Top 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDEV with highest average IOPS",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk_avg(5, hv_ldev_iops{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{ldev}}"
      }
     ]
    },
    {
     "title": "LDEV with highest average Throughput",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "topk_avg(5, hv_ldev_transfer{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{ldev}}"
      }
     ]
    },
    {
     "title": "LDEV with highest average Latency",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk_avg(5, hv_ldev_latency{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{ldev}}"
      }
     ]
    },
    {
     "title": "LDEV with highest maximum IOPS",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk_max(5, hv_ldev_iops{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{ldev}}"
      }
     ]
    },
    {
     "title": "LDEV with highest maximum Throughput",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "topk_max(5, hv_ldev_transfer{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{ldev}}"
      }
     ]
    },
    {
     "title": "LDEV with highest maximum Latency",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk_max(5, hv_ldev_latency{storagename=~\"$System\", storagetype=~\"$Type\"})",
       "legendFormat": "{{storagename}}.{{ldev}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HSD Top 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "HSD with highest average IOPS",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk_avg(5,sum by(hsd, storagename) (hv_lu_iops{storagename=~\"$System\", storagetype=~\"$Type\"}))",
       "legendFormat": "{{storagename}}.{{hsd}}"
      }
     ]
    },
    {
     "title": "HSD with highest average Throughput",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "topk_avg(5,sum by(hsd, storagename) (hv_lu_transfer{storagename=~\"$System\", storagetype=~\"$Type\", port=~\"CL[13579]-.\"}))",
       "legendFormat": "{{storagename}}.{{hsd}}"
      }
     ]
    },
    {
     "title": "HSD with highest average Latency",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk_avg(5,max by(hsd, storagename) (hv_lu_latency{storagename=~\"$System\", storagetype=~\"$Type\" ,port=~\"CL[13579]-.\"}))",
       "legendFormat": "{{storagename}}.{{hsd}}"
      }
     ]
    },
    {
     "title": "HSD with highest maximum IOPS",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk_max(5,sum by(hsd, storagename) (hv_lu_iops{storagename=~\"$System\", storagetype=~\"$Type\" ,port=~\"CL[13579]-.\"}))",
       "legendFormat": "{{storagename}}.{{hsd}}"
      }
     ]
    },
    {
     "title": "HSD with highest maximum Throughput",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "topk_max(5,sum by(hsd, storagename) (hv_lu_transfer{storagename=~\"$System\", storagetype=~\"$Type\" ,port=~\"CL[13579]-.\"}))",
       "legendFormat": "{{storagename}}.{{hsd}}"
      }
     ]
    },
    {
     "title": "HSD with highest maximum Latency",
     "type": "table",
     "description": "uses MetricQL function",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk_max(5,max by(hsd, storagename) (hv_lu_latency{storagename=~\"$System\", storagetype=~\"$Type\" ,port=~\"CL[13579]-.\"}))",
       "legendFormat": "{{storagename}}.{{hsd}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Utilization of all pools: $System",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum(hv_capacity_pool_total{storagetype=~\"$Type\", storagename=~\"$System\"})",
       "legendFormat": "Total Capacity $System"
      },
      {
       "expr": "sum(hv_capacity_pool_used{storagetype=~\"$Type\", storagename=~\"$System\"})",
       "legendFormat": "Used Capacity $System"
      }
     ]
    },
    {
     "title": "Capactiy Utilization",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hv_capacity_pool_percentused{storagetype=~\"$Type\", storagename=~\"$System\"}) / count(hv_capacity_pool_percentused{storagetype=~\"$Type\", storagename=~\"$System\"})",
       "legendFormat": "Used Capacity $System"
      },
      {
       "expr": "sum(hv_capacity_pool_percentavailable{storagetype=~\"$Type\", storagename=~\"$System\"}) / count(hv_capacity_pool_percentavailable{storagetype=~\"$Type\", storagename=~\"$System\"})",
       "legendFormat": "Available Capacity $System"
      }
     ]
    },
    {
     "title": "Pool with highest Usage Rate",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "hv_capacity_pool_percentused{storagetype=~\"$Type\", storagename=~\"$System\"}",
       "legendFormat": "{{storagename}}.{{poolid}}"
      }
     ]
    }
   ]
  }
 ]
}