{
 "title": "HV: Historical Pool Performance",
 "description": "Historical data based on Export Tool dump",
 "tags": [
  "Hitachi Vantara",
  "Historical"
 ],
 "time": { "from": "now-6h", "to": "now-1h" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\"},storagetype)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_port_iops{entity=\"physical\",storagetype=~\"$Type\"},storagename)"
    }
   },
   {
    "name": "Pool",
    "query": {
     "query": "label_values(hv_ldev_iops{entity=\"physical\",storagetype=~\"$Type\",storagename=~\"$System\"},p_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Port Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool IOPS: $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(storagename) (hv_ldev_iops{type=\"DP\", storagetype=~\"$Type\", storagename=~\"$System\", p_id=~\"$Pool\"})",
     "legendFormat": "{{storagename}} - $Pool"
    }
   ]
  },
  {
   "title": "Pool Throughput: $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by(storagename) (hv_ldev_transfer{type=\"DP\", storagetype=~\"$Type\", storagename=~\"$System\", p_id=~\"$Pool\"})",
     "legendFormat": "{{storagename}} - $Pool"
    }
   ]
  },
  {
   "title": "Pool average Latency: $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by(storagename) (hv_ldev_latency{type=\"DP\", storagetype=~\"$Type\", storagename=~\"$System\", p_id=~\"$Pool\"})",
     "legendFormat": "{{storagename}} - $Pool"
    }
   ]
  },
  { "title": "Top 5 LDEVs per Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$System: LDEVs with highest average IOPS in pool: $Pool",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk_avg(5,hv_ldev_iops{type=\"DP\",storagetype=~\"$Type\", storagename=~\"$System\", p_id=~\"$Pool\"})",
     "legendFormat": "{{storagename}} - {{ldev}}"
    }
   ]
  },
  {
   "title": "$System: LDEVs with highest maximum IOPS in pool: $Pool",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk_max(5,hv_ldev_iops{type=\"DP\",storagetype=~\"$Type\", storagename=~\"$System\", p_id=~\"$Pool\"})",
     "legendFormat": "{{storagename}} - {{ldev}}"
    }
   ]
  }
 ]
}