{
 "title": "HV: Historical LDEV Details",
 "description": "Historical data based on Export Tool dump",
 "tags": [
  "Hitachi Vantara",
  "Historical"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_ldev_iops,storagetype)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_ldev_iops{storagetype=\"$Type\"},storagename)"
    }
   },
   {
    "name": "Pool",
    "query": {
     "query": "label_values(hv_ldev_iops{storagetype=\"$Type\",storagename=\"$System\",type=\"DP\"},p_id)"
    }
   },
   {
    "name": "LDEV",
    "query": {
     "query": "label_values(hv_ldev_iops{storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\"},ldev)"
    }
   }
  ]
 },
 "panels": [
  { "title": "LDEV Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LDEV IOPS for $LDEV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "hv_ldev_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"}",
     "legendFormat": "{{ldev}}"
    }
   ]
  },
  {
   "title": "LDEV Throughput for $LDEV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "hv_ldev_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"}",
     "legendFormat": "{{ldev}}"
    }
   ]
  },
  {
   "title": "LDEV Latency for $LDEV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hv_ldev_latency{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"}",
     "legendFormat": "{{ldev}}"
    }
   ]
  },
  { "title": "Read / Write Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Read & Write IOPS for $LDEV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "hv_ldev_read_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"}",
     "legendFormat": "READ_IOPS"
    },
    {
     "expr": "hv_ldev_write_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"}",
     "legendFormat": "WRITE_IOPS"
    }
   ]
  },
  {
   "title": "Read & Write Ration on IOPS for $LDEV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hv_ldev_read_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} / (hv_ldev_read_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} + hv_ldev_write_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"})",
     "legendFormat": "Read Percentage"
    },
    {
     "expr": "hv_ldev_write_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} / (hv_ldev_read_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} + hv_ldev_write_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"})",
     "legendFormat": "Write Percentage"
    }
   ]
  },
  {
   "title": "Read / Write IO Ratio for LDEV $LDEV",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hv_ldev_read_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} ",
     "legendFormat": "Reads"
    },
    {
     "expr": "hv_ldev_write_iops{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} ",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Read & Write Latency for $LDEV",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hv_ldev_read_latency{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"}",
     "legendFormat": "READ_LATENCY"
    },
    {
     "expr": "hv_ldev_write_latency{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"}",
     "legendFormat": "WRITE_LATENCY"
    }
   ]
  },
  {
   "title": "Read & Write Throughput for $LDEV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "hv_ldev_read_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"}",
     "legendFormat": "READ_TRANSFER"
    },
    {
     "expr": "hv_ldev_write_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"}",
     "legendFormat": "WRITE_TRANSFER"
    }
   ]
  },
  {
   "title": "Read & Write Ration on Throughput for $LDEV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hv_ldev_read_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} / (hv_ldev_read_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} + hv_ldev_write_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"})",
     "legendFormat": "Read Percentage"
    },
    {
     "expr": "hv_ldev_write_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} / (hv_ldev_read_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} + hv_ldev_write_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"})",
     "legendFormat": "Write Percentage"
    }
   ]
  },
  {
   "title": "Read / Write Throughput Ratio for LDEV $LDEV",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hv_ldev_read_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} ",
     "legendFormat": "Reads"
    },
    {
     "expr": "hv_ldev_write_transfer{storagetype=\"$Type\", storagename=\"$System\", p_id=\"000\", type=\"DP\", ldev=\"$LDEV\"} ",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Sequential / Random Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Random & Sequential IOPS for LDEV $LDEV",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum({__name__=~\"hv_ldev_rnd_.+_iops\",storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"})",
       "legendFormat": "Random IOPS"
      },
      {
       "expr": "sum({__name__=~\"hv_ldev_seq_.+_iops\",storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"})",
       "legendFormat": "Sequential IOPS"
      }
     ]
    },
    {
     "title": "Random & Sequential IOPS Ratio for LDEV $LDEV",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum({__name__=~\"hv_ldev_rnd_.+_iops\",storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"})",
       "legendFormat": "Random IOPS"
      },
      {
       "expr": "sum({__name__=~\"hv_ldev_seq_.+_iops\",storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"})",
       "legendFormat": "Sequential IOPS"
      }
     ]
    },
    {
     "title": "Random & Sequential Read IOPS for LDEV $LDEV",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "hv_ldev_rnd_read_iops{storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"}",
       "legendFormat": "Random Read IOPS"
      },
      {
       "expr": "hv_ldev_seq_read_iops{storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"}",
       "legendFormat": "Sequential Read IOPS"
      }
     ]
    },
    {
     "title": "Random & Sequential Read IOPS Ratio for LDEV $LDEV",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "hv_ldev_rnd_read_iops{storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"}",
       "legendFormat": "Random Read IOPS"
      },
      {
       "expr": "hv_ldev_seq_read_iops{storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"}",
       "legendFormat": "Sequential Read IOPS"
      }
     ]
    },
    {
     "title": "Random & Sequential Write IOPS for LDEV $LDEV",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "hv_ldev_rnd_write_iops{storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"}",
       "legendFormat": "Random Write IOPS"
      },
      {
       "expr": "hv_ldev_seq_write_iops{storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"}",
       "legendFormat": "Sequential Write IOPS"
      }
     ]
    },
    {
     "title": "Random & Sequential Read IOPS Ratio for LDEV $LDEV",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "hv_ldev_rnd_write_iops{storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"}",
       "legendFormat": "Random Write IOPS"
      },
      {
       "expr": "hv_ldev_seq_write_iops{storagetype=\"$Type\",storagename=\"$System\",type=\"DP\",p_id=\"$Pool\",ldev=\"$LDEV\"}",
       "legendFormat": "Sequential Write IOPS"
      }
     ]
    }
   ]
  },
  {
   "title": "LDEV Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDEV Capacity and Used for $LDEV",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "hv_capacity_ldev_total{storagetype=\"$Type\", storagename=\"$System\", ldevtype=\"DP\", poolid=\"$Pool\", ldev=\"$LDEV\"}",
       "legendFormat": "Capacity"
      },
      {
       "expr": "hv_capacity_ldev_used{storagetype=\"$Type\", storagename=\"$System\", ldevtype=\"DP\", poolid=\"$Pool\", ldev=\"$LDEV\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Tier Utilization for LDEV: $LDEV",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "hv_capacity_ldev_tier1{storagetype=\"$Type\", storagename=\"$System\", ldevtype=\"DP\", poolid=\"$Pool\", ldev=\"$LDEV\"}",
       "legendFormat": "Tier 1"
      },
      {
       "expr": "hv_capacity_ldev_tier2{storagetype=\"$Type\", storagename=\"$System\", ldevtype=\"DP\", poolid=\"$Pool\", ldev=\"$LDEV\"}",
       "legendFormat": "Tier 2"
      },
      {
       "expr": "hv_capacity_ldev_tier3{storagetype=\"$Type\", storagename=\"$System\", ldevtype=\"DP\", poolid=\"$Pool\", ldev=\"$LDEV\"}",
       "legendFormat": "Tier 3"
      }
     ]
    }
   ]
  }
 ]
}