{
 "title": "HV: Historical HSD Details",
 "description": "Hitachi Vantara: Host Storage Domain Details - Historical data based on Export Tool dump",
 "tags": [
  "Hitachi Vantara",
  "Historical"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_ldev_iops,storagetype)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_ldev_iops{storagetype=\"$Type\"},storagename)"
    }
   },
   {
    "name": "HSD",
    "query": {
     "query": "label_values(hv_lu_iops{storagetype=\"$Type\",storagename=\"$System\"},hsd)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HSD Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HSD IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(hsd) (hv_lu_iops{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
     "legendFormat": "{{ldev}}"
    }
   ]
  },
  {
   "title": "HSD Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by(hsd) (hv_lu_transfer{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
     "legendFormat": "{{ldev}}"
    }
   ]
  },
  {
   "title": "HSD Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by(hsd) (hv_lu_latency{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
     "legendFormat": "{{ldev}}"
    }
   ]
  },
  {
   "title": "HSD Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read & Write Throughput for HSD",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(hsd) (hv_lu_read_transfer{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "READ_TRANSFER"
      },
      {
       "expr": "sum by(hsd) (hv_lu_write_transfer{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "WRITE_TRANSFER"
      }
     ]
    },
    {
     "title": "Read & Write Ratio on Throughput",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(hv_lu_read_transfer{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"}) / (sum(hv_lu_read_transfer{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"}) + sum(hv_lu_write_transfer{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"}))",
       "legendFormat": "Read Percentage"
      },
      {
       "expr": "sum(hv_lu_write_transfer{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"}) / (sum(hv_lu_read_transfer{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"}) + sum(hv_lu_write_transfer{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"}))",
       "legendFormat": "Write Percentage"
      }
     ]
    },
    {
     "title": "Read & Write Latency for HSD",
     "type": "timeseries",
     "description": "Average Latency",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by(hsd) (hv_lu_read_latency{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "READ_LATENCY"
      },
      {
       "expr": "avg by(hsd) (hv_lu_write_latency{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "WRITE_LATENCY"
      }
     ]
    }
   ]
  },
  {
   "title": "HSD Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "HSD Capacity and Used for $HSD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "sum by(hsd) (hv_capacity_lu_total{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum by(hsd) (hv_capacity_lu_used{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Tier Utilization for HSD: $HSD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "sum by(hsd) (hv_capacity_lu_tier1{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "Tier 1"
      },
      {
       "expr": "sum by(hsd) (hv_capacity_lu_tier2{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "Tier 2"
      },
      {
       "expr": "sum by(hsd) (hv_capacity_lu_tier3{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "Tier 3"
      }
     ]
    }
   ]
  },
  {
   "title": "LUN Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "LUN IOPS",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "max by(ldev, hsd) (hv_lu_iops{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "{{hsd}} - {{ldev}}"
      }
     ]
    },
    {
     "title": "LUN Throughput",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "max by(ldev, hsd) (hv_lu_transfer{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "{{hsd}} - {{ldev}}"
      }
     ]
    },
    {
     "title": "LUN Average Latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by(ldev, hsd) (hv_lu_latency{storagetype=\"$Type\", storagename=\"$System\", hsd=~\"$HSD\"})",
       "legendFormat": "{{hsd}} - {{ldev}}"
      }
     ]
    }
   ]
  }
 ]
}