{
 "title": "HV: Realtime GAD VSM Details",
 "description": "Global Active Device - Virtual Storage Machine Details - Realtime data based on Ops Center Analyzer REST API",
 "tags": [
  "Hitachi Vantara",
  "Realtime",
  "todo"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_ldev_realtime_read_io_rate,storagetype)"
    }
   },
   {
    "name": "VSM",
    "query": {
     "query": "label_values(hv_ldev_realtime_read_io_rate{storagetype=~\"$Type\", entity=\"virtual\"},storagename)"
    }
   },
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_ldev_realtime_read_io_rate{storagetype=~\"$Type\", entity=\"virtual\",storagename=~\"$VSM\"},phys_storagename)"
    }
   },
   {
    "name": "Port",
    "query": {
     "query": "label_values(hv_lu_iops{storagetype=~\"$Type\", entity=\"virtual\",storagename=\"$VSM\"},port)"
    }
   }
  ]
 },
 "panels": [
  { "title": "VSM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total amount of IOPS per Site for $VSM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(phys_storagename) (hv_ldev_realtime_read_io_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"}+hv_ldev_realtime_write_io_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}}"
    }
   ]
  },
  {
   "title": "Total transfer per Site for $VSM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by(phys_storagename) (hv_ldev_realtime_read_xfer_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"} + hv_ldev_realtime_write_xfer_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}}"
    }
   ]
  },
  {
   "title": "Average Read / Write Latency on $VSM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by(phys_storagename) (hv_ldev_realtime_read_response_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}} READ_LATENCY"
    },
    {
     "expr": "avg by(phys_storagename) (hv_ldev_realtime_write_response_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}} WRITE_LATENCY"
    }
   ]
  },
  { "title": "VSM IO Read / Write Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Read IOPS per Site for $VSM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(phys_storagename) (hv_ldev_realtime_read_io_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}}"
    }
   ]
  },
  {
   "title": "Current Read I/O Distribution",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(phys_storagename) (hv_ldev_realtime_read_io_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}}"
    }
   ]
  },
  {
   "title": "Write IOPS per Site for $VSM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(phys_storagename) (hv_ldev_realtime_write_io_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}}"
    }
   ]
  },
  {
   "title": "Current Write I/O Distribution",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(phys_storagename) (hv_ldev_realtime_write_io_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}}"
    }
   ]
  },
  {
   "title": "Read transfer per Site for $VSM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by(phys_storagename) (hv_ldev_realtime_read_xfer_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}}"
    }
   ]
  },
  {
   "title": "Current Read transfer Distribution",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(phys_storagename) (hv_ldev_realtime_read_xfer_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}}"
    }
   ]
  },
  {
   "title": "Write transfer per Site for $VSM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by(phys_storagename) (hv_ldev_realtime_write_xfer_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}}"
    }
   ]
  },
  {
   "title": "Current Write transfer Distribution",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(phys_storagename) (hv_ldev_realtime_write_xfer_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\"})",
     "legendFormat": "{{phys_storagename}}"
    }
   ]
  },
  {
   "title": "VSM Port Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Port IOPS for $VSM",
     "type": "timeseries",
     "description": "Port query relies on Export Tool information, panel will not work if only realtime data is collected",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "hv_port_realtime_avg_io_rate{storagetype=\"$Type\", storagename=~\"$System\", port_name=~\"$Port\"}",
       "legendFormat": "{{storagename}} - {{port_name}}"
      }
     ]
    },
    {
     "title": "Average Port Transfer for $VSM",
     "type": "timeseries",
     "description": "Port query relies on Export Tool information, panel will not work if only realtime data is collected",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "hv_port_realtime_avg_xfer_rate{storagetype=\"$Type\", storagename=~\"$System\", port_name=~\"$Port\"}",
       "legendFormat": "{{storagename}} - {{port_name}}"
      }
     ]
    },
    {
     "title": "Average Port Latency for $VSM",
     "type": "timeseries",
     "description": "Port query relies on Export Tool information, panel will not work if only realtime data is collected",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "hv_port_realtime_avg_response_rate{storagetype=\"$Type\", storagename=~\"$System\", port_name=~\"$Port\"}",
       "legendFormat": "{{storagename}} - {{port_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top LDEVs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 LDEV with highest avg IOPS",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk_avg(10,hv_ldev_realtime_read_io_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\", type=\"dp\"} + hv_ldev_realtime_write_io_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\", type=\"dp\"})",
       "legendFormat": "{{ldev_number}}"
      }
     ]
    },
    {
     "title": "Top 10 LDEV with highest avg Transfer",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "topk_avg(10,hv_ldev_realtime_read_xfer_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\", type=\"dp\"} + hv_ldev_realtime_write_xfer_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\", type=\"dp\"})",
       "legendFormat": "{{ldev_number}}"
      }
     ]
    },
    {
     "title": "Top 10 LDEV with highest avg Read Latency",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "topk_avg(10,hv_ldev_realtime_read_response_rate{entity=\"virtual\", storagename=\"$VSM\", storagetype=\"$Type\", type=\"dp\"})",
       "legendFormat": "{{ldev_number}}"
      }
     ]
    }
   ]
  }
 ]
}