{
 "title": "HV: Realtime GAD LDEV Details",
 "description": "Realtime data based on Ops Center Analyzer REST API",
 "tags": [
  "Hitachi Vantara",
  "Realtime"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": {
     "query": "label_values(hv_ldev_realtime_read_io_rate,storagetype)"
    }
   },
   {
    "name": "VSM",
    "query": {
     "query": "label_values(hv_ldev_realtime_read_io_rate{storagetype=~\"$Type\", entity=\"virtual\"},storagename)"
    }
   },
   {
    "name": "Pool",
    "query": {
     "query": "label_values(hv_ldev_realtime_read_io_rate{storagetype=~\"$Type\", entity=\"virtual\"},pool_id)"
    }
   },
   {
    "name": "VLDEV",
    "query": {
     "query": "label_values(hv_ldev_realtime_read_io_rate{storagetype=~\"$Type\",storagename=~\"$VSM\",type=\"dp\",entity=\"virtual\",pool_id=~\"$Pool\"},ldev_number)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Read / Write IOPS for $VLDEV on $VSM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "hv_ldev_realtime_read_io_rate{entity=\"virtual\", ldev_number=\"$VLDEV\", storagename=\"$VSM\", storagetype=\"$Type\", pool_id=\"$Pool\"}",
     "legendFormat": "{{phys_storagename}} READ_IO_RATE"
    },
    {
     "expr": "hv_ldev_realtime_write_io_rate{entity=\"virtual\", ldev_number=\"$VLDEV\", storagename=\"$VSM\", storagetype=\"$Type\", pool_id=\"$Pool\"}",
     "legendFormat": "{{phys_storagename}} WRITE_IO_RATE"
    }
   ]
  },
  {
   "title": "Read / Write Transfer for $VLDEV on $VSM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "hv_ldev_realtime_read_xfer_rate{entity=\"virtual\", ldev_number=\"$VLDEV\", storagename=\"$VSM\", storagetype=\"$Type\", pool_id=\"$Pool\"}",
     "legendFormat": "{{phys_storagename}} READ_XFER_RATE"
    },
    {
     "expr": "hv_ldev_realtime_write_xfer_rate{entity=\"virtual\", ldev_number=\"$VLDEV\", storagename=\"$VSM\", storagetype=\"$Type\", pool_id=\"$Pool\"}",
     "legendFormat": "{{phys_storagename}} WRITE_XFER_RATE"
    }
   ]
  },
  {
   "title": "Read / Write Latency for $VLDEV on $VSM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "hv_ldev_realtime_read_response_rate{entity=\"virtual\", ldev_number=\"$VLDEV\", storagename=\"$VSM\", storagetype=\"$Type\", pool_id=\"$Pool\"}",
     "legendFormat": "{{phys_storagename}} READ_LATENCY"
    },
    {
     "expr": "hv_ldev_realtime_write_response_rate{entity=\"virtual\", ldev_number=\"$VLDEV\", storagename=\"$VSM\", storagetype=\"$Type\", pool_id=\"$Pool\"}",
     "legendFormat": "{{phys_storagename}} WRITE_LATENCY"
    }
   ]
  }
 ]
}