{
 "title": "HV: Realtime System Performance",
 "description": "Realtime data based on Ops Center Analyzer REST API",
 "tags": [
  "Hitachi Vantara",
  "Realtime"
 ],
 "time": { "from": "now-6h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "System",
    "query": {
     "query": "label_values(hv_port_realtime_avg_io_rate,storagename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System IOPS and Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total System IOPS for $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(hv_port_realtime_avg_io_rate{storagename=\"$System\"})"
    }
   ]
  },
  {
   "title": "Total System Throughput for $System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(hv_port_realtime_avg_xfer_rate{storagename=\"$System\"})"
    }
   ]
  },
  {
   "title": "READ / WRITE IOPS for $System",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "hv_system_realtime_read_io_rate{storagename=\"$System\"}",
     "legendFormat": "READ_IO_RATE"
    },
    {
     "expr": "hv_system_realtime_write_io_rate{storagename=\"$System\"}",
     "legendFormat": "WRITE_IO_RATE"
    }
   ]
  },
  {
   "title": "READ / WRITE IO Ration for $System",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hv_system_realtime_read_io_rate{storagename=\"$System\"}",
     "legendFormat": "READ_IO_RATE"
    },
    {
     "expr": "hv_system_realtime_write_io_rate{storagename=\"$System\"}",
     "legendFormat": "WRITE_IO_RATE"
    }
   ]
  },
  {
   "title": "READ / WRITE Throughput for $System",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "hv_system_realtime_read_xfer_rate{storagename=\"$System\"}",
     "legendFormat": "READ_IO_RATE"
    },
    {
     "expr": "hv_system_realtime_write_xfer_rate{storagename=\"$System\"}",
     "legendFormat": "WRITE_IO_RATE"
    }
   ]
  },
  {
   "title": "READ / WRITE IO Ration for $System",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hv_system_realtime_read_xfer_rate{storagename=\"$System\"}",
     "legendFormat": "READ_IO_RATE"
    },
    {
     "expr": "hv_system_realtime_write_xfer_rate{storagename=\"$System\"}",
     "legendFormat": "WRITE_IO_RATE"
    }
   ]
  },
  {
   "title": "Multiprocessor Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Multiprocessor Utilization: $System",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "hv_prcs_realtime_processor_busy_rate{storagename=\"$System\", processor_id=\"_Total\"}",
       "legendFormat": "{{adaptor_id}}"
      }
     ]
    },
    {
     "title": "Current Global Mutliprocessor Utilization $System",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 10, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hv_prcs_realtime_processor_busy_rate{storagename=\"$System\", processor_id=~\"_Total\"})"
      }
     ]
    },
    {
     "title": "Max Multiprocessor Buffer Length: $System",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hv_prcs_realtime_max_buffer_io_count{storagename=\"$System\", processor_id=~\"_Total\"}",
       "legendFormat": "{{adaptor_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Cache Write Pending: $System",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "hv_cache_realtime_cache_write_pending_rate{label=\"ALL\", storagename=\"$System\"}",
       "legendFormat": "CACHE WRITE PENDING RATE"
      }
     ]
    },
    {
     "title": "Current Global Cache Write Pending $System",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 4, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hv_cache_realtime_cache_write_pending_rate{label=\"ALL\", storagename=\"$System\"}"
      }
     ]
    },
    {
     "title": "Current Global Cache Utiliation $System",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 4, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hv_cache_realtime_max_cache_memory_usage_rate{label=\"ALL\", storagename=\"$System\"}"
      }
     ]
    },
    {
     "title": "System Cache Write Pending: $System",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "hv_cache_realtime_cache_memory_usage_rate{label=\"ALL\", storagename=\"$System\"}",
       "legendFormat": "CACHE MEMORY USAGE RATE"
      }
     ]
    }
   ]
  },
  {
   "title": "Channel Adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Channel Adapter IOPS of $System",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "hv_chs_realtime_avg_io_rate{storagename=\"$System\"}",
       "legendFormat": "{{cha_name}}"
      }
     ]
    },
    {
     "title": "Channel Adapter Through of $System",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "hv_chs_realtime_avg_xfer_rate{storagename=\"$System\"}",
       "legendFormat": "{{cha_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RAID Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max. Parity Group Utilization for $System",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "hv_rgs_realtime_max_busy_rate{storagename=\"$System\"}",
       "legendFormat": "{{raid_group_number}}"
      }
     ]
    },
    {
     "title": "Current Average RAID Group Utilization",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hv_rgs_realtime_max_busy_rate{storagename=\"$System\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Distribution of RAID Group Busy for $System",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(hv_rgs_realtime_max_busy_rate{storagename=\"$System\"})",
       "legendFormat": "{{raid_group_number}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Port Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Realtime Port IOPS for $System",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sort_desc(hv_port_realtime_avg_io_rate{storagename=\"$System\"})",
       "legendFormat": "{{port_name}}"
      }
     ]
    },
    {
     "title": "Realtime Port Throughput for $System",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "sort_desc(hv_port_realtime_avg_xfer_rate{storagename=\"$System\"})",
       "legendFormat": "{{port_name}}"
      }
     ]
    },
    {
     "title": "Port with highest IOPS on $System",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "hv_port_realtime_avg_io_rate{storagename=\"$System\"} and topk(20, hv_port_realtime_avg_io_rate{storagename=\"$System\"} @ end())",
       "legendFormat": "{{port_name}}"
      }
     ]
    },
    {
     "title": "Port with highest Throughput on $System",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "hv_port_realtime_avg_xfer_rate{storagename=\"$System\"} and topk(20, hv_port_realtime_avg_xfer_rate{storagename=\"$System\"} @ end())",
       "legendFormat": "{{port_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LDEV Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDEV of $System with hight average IOPS",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum({__name__=~\"hv_ldev_realtime_.*_io_rate\",storagename=\"$System\",type=\"dp\"}) by (ldev_number) and topk(20,sum({__name__=~\"hv_ldev_realtime_.*_io_rate\",storagename=\"$System\",type=\"dp\"}) by (ldev_number) @ end())",
       "legendFormat": "{{ldev_number}}"
      }
     ]
    },
    {
     "title": "LDEV of $System with hight average Throughput",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "sum({__name__=~\"hv_ldev_realtime_.*_xfer_rate\",storagename=\"$System\",type=\"dp\"}) by (ldev_number) and topk(20,sum({__name__=~\"hv_ldev_realtime_.*_xfer_rate\",storagename=\"$System\",type=\"dp\"}) by (ldev_number) @ end())",
       "legendFormat": "{{ldev_number}}"
      }
     ]
    }
   ]
  }
 ]
}