name: check-syntax

on: workflow_dispatch

jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.26'
    - name: perl -V
      run: perl -V
    - run: cpanm --installdeps .
    - run: prove -lv t
